# dirname to find data
train_name: "whisper"
train_id: "1"
model_name: "medium"
train_root: /home/barb_cinnamon_is/jnas_hy-parsed
train_manifest: /home/barb_cinnamon_is/jnas_hy-parsed/test_manifest.csv
val_root: /home/barb_cinnamon_is/jnas_hy-parsed
val_manifest: /home/barb_cinnamon_is/jnas_hy-parsed/test_manifest.csv
test_root: /home/barb_cinnamon_is/jnas_hy-parsed
test_manifest: /home/barb_cinnamon_is/jnas_hy-parsed/test_manifest.csv
path:
  log: "./log"
  checkpoint: "./checkpoint"  # dir to save model

data:
  audio_sampling_rate: 16000
  audio_max_length: 480000
  lang: "ja"
  dict_path: jnas_boost_dictionary_algor.csv
  frontend: None
  text_max_length: 120
  train_ratio: 0.8
  val_ratio: 0.1
  timestamps: False

train:
  batch_size: 2
  seed: 7747
  learning_rate: 0.0005
  weight_decay: 0.01
  adam_epsilon: 0.00000001
  warmup_steps: 2
  num_worker: 4
  num_train_epochs: 10
  gradient_accumulation_steps: 8

inference:
  using_prompt: True
  dict_coeff: 0.2
  ban_dict_coeff: 0.0
  epoch_index: 4

  


